import { Tray, Menu, nativeImage } from 'electron'
import { getMainWindow } from './windows'

// Minimal embedded tray icon so no binary asset is needed.
// Branded 32x32 coral "A" monogram on charcoal (generated by scripts/gen-icon.cjs).
const ICON_DATA_URL =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAk0lEQVR4nO3XwQ2AIAyFYYYxrOQozuo0cvMiLbxXijTBhCP+X4gxNCXhyfl4Ri6p4xqFMLPiVcTs+AcRFnBf57towIi4CRESUIuziHgALc4gNgAC9MRRRByAFrIgYgCQo0cRG9AEWOI9iLUBzAvRPfEA7EcLAyw/F2Svei/0PoHmrZiJI3vXmQt+H82WGE69MVKnACEDk0jIi56FAAAAAElFTkSuQmCC'

let tray: Tray | null = null

export function createTray(onDisableStealth: () => void): void {
  if (tray) return
  tray = new Tray(nativeImage.createFromDataURL(ICON_DATA_URL))

  const menu = Menu.buildFromTemplate([
    { label: '◆ Aplomb — Stealth Mode', enabled: false },
    { type: 'separator' },
    { label: 'Show App', click: () => getMainWindow()?.show() },
    {
      label: 'Copy Last Answer (Ctrl+Shift+C)',
      click: () => getMainWindow()?.webContents.send('copy-last-answer'),
    },
    { type: 'separator' },
    { label: 'End Session', click: () => getMainWindow()?.webContents.send('end-session') },
    { label: 'Disable Stealth Mode', click: () => onDisableStealth() },
  ])

  tray.setToolTip('Aplomb — Active')
  tray.setContextMenu(menu)
}

export function destroyTray(): void {
  tray?.destroy()
  tray = null
}
